name: Deploy
on:
  push:
    branches: [master]
jobs:
  deploy:
    if: startsWith(github.event.head_commit.message, 'chore(release):')
    runs-on: ubuntu-latest
    env:
      FF_APP_ID: "{6b982795-4e75-4bc0-a1d8-616f4eb39970}"
    steps:
    - uses: actions/checkout@v2
    - run: git archive -o package.zip HEAD
    - uses: trmcnvn/firefox-addon@v1
      with:
        uuid: "${{ env.FF_APP_ID }}"
        xpi: package.zip
        manifest: ./manifest.json
        api-key: ${{ secrets.FF_JWT_ISSUER }}
        api-secret: ${{ secrets.FF_JWT_SECRET }}
